name: Deploy to Vercel

on:
  push:
    branches: [main]

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

jobs:
  deploy:
    name: Deploy to Production
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

      - name: Build Project Artifacts
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}

      - name: Verify Deployment
        run: |
          echo "Deployment completed successfully"
          echo "Running health check..."
          sleep 30
          curl -f ${{ secrets.PRODUCTION_URL }}/api/health || exit 1

  post-deploy:
    name: Post-Deployment Tasks
    runs-on: ubuntu-latest
    needs: deploy
    environment: production

    steps:
      - name: Run Database Migrations
        run: |
          echo "Database migrations would run here"
          # In a real scenario, you might run:
          # npx drizzle-kit push --config=drizzle.config.production.ts

      - name: Warm Up Application
        run: |
          echo "Warming up application..."
          curl -f ${{ secrets.PRODUCTION_URL }}/api/health
          curl -f ${{ secrets.PRODUCTION_URL }}/

      - name: Notify Team
        if: success()
        run: |
          echo "Deployment successful! Notification would be sent here."
          # Could integrate with Slack, Discord, or email notifications

      - name: Rollback on Failure
        if: failure()
        run: |
          echo "Deployment failed! Rollback would be triggered here."
          # Could trigger automatic rollback procedures